/**
 * Novarite × QVAC — Shared game catalogue and text utilities.
 *
 * Imported by recommend.mjs (QVAC CLI) and server.mjs (API server).
 * The frontend mirrors this data in frontend/lib/gameData.ts.
 *
 * novariteAvailable: true  → game is hosted on the Novarite platform.
 * novariteAvailable: false → reference recommendation only; not hosted on Novarite.
 */

export const GAMES = [

  // ── Novarite games ─────────────────────────────────────────────────────────

  {
    id: "graverush",
    title: "GraveRush",
    genre: "FPS",
    tags: ["fps", "zombie", "survival", "wave-based", "godot", "shooter", "retro", "first-person", "free", "downloadable", "windows", "horror"],
    description: "A wave-based zombie survival FPS built in Godot with retro visuals. Fight off undead hordes in first-person across escalating waves. Free Windows download available now on Novarite.",
    novariteAvailable: true,
    novariteNote: "Available on Novarite",
    length: "medium",
    platforms: ["Windows"],
    popularity: "indie",
  },
  {
    id: "little-runmo",
    title: "Little Runmo - The Game",
    genre: "Platformer",
    tags: ["platformer", "adventure", "demo", "short", "downloadable", "cartoon", "funny", "fan-game", "windows", "run", "jump", "cute"],
    description: "A short platformer adventure based on the beloved YouTube animation by Gooseworx. Run, jump, and dodge through whimsical hazards. Demo available on Novarite.",
    novariteAvailable: true,
    novariteNote: "Available on Novarite",
    length: "short",
    platforms: ["Windows"],
    popularity: "indie",
  },

  // ── Metroidvania / Soulslike / Hard Action ─────────────────────────────────

  {
    id: "hollow-knight",
    title: "Hollow Knight",
    genre: "Metroidvania",
    tags: ["metroidvania", "difficult", "atmospheric", "underground", "bug", "dark", "exploration", "boss-rush", "action", "hand-drawn", "soulslike", "hard"],
    description: "Explore a vast underground kingdom of insects in this stunning hand-drawn metroidvania. Deep lore, precise combat, and hundreds of rooms to discover beneath a fallen kingdom.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Mac", "Linux", "Console"],
    popularity: "indie classic",
  },
  {
    id: "blasphemous",
    title: "Blasphemous",
    genre: "Soulslike Metroidvania",
    tags: ["soulslike", "metroidvania", "dark", "pixel-art", "religious", "horror", "difficult", "brutal", "action", "gore", "atmospheric", "spanish"],
    description: "A brutal soulslike set in a dark religious world soaked in guilt and grotesque beauty. Pixel-art combat demands precision — every death is a penance.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Mac", "Linux", "Console"],
    popularity: "indie classic",
  },
  {
    id: "blasphemous-2",
    title: "Blasphemous 2",
    genre: "Soulslike Metroidvania",
    tags: ["soulslike", "metroidvania", "dark", "pixel-art", "religious", "horror", "difficult", "action", "gore", "atmospheric", "sequel"],
    description: "The Penitent One returns in a grander, more fluid sequel. Three weapons offer distinct playstyles across a baroque world of penitence and twisted faith.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Mac", "Linux", "Console"],
    popularity: "popular",
  },
  {
    id: "dead-cells",
    title: "Dead Cells",
    genre: "Roguelite Metroidvania",
    tags: ["roguelite", "metroidvania", "action", "fast-paced", "procedural", "difficult", "fluid", "build", "run-based", "pixel-art", "replay"],
    description: "A fast, punishing roguelite with tight action-platformer combat and procedurally generated dungeons. Every run unlocks new weapons and paths through a crumbling castle.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Mac", "Linux", "Console"],
    popularity: "indie classic",
  },
  {
    id: "salt-and-sanctuary",
    title: "Salt and Sanctuary",
    genre: "Soulslike",
    tags: ["soulslike", "2d", "dark-fantasy", "action-rpg", "difficult", "dark", "grim", "boss", "rpg", "underground"],
    description: "A 2D dark-fantasy soulslike with punishing bosses, deep character builds, and grim hand-drawn environments. The spiritual 2D cousin of Dark Souls.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Mac", "Linux", "Console"],
    popularity: "cult favorite",
  },
  {
    id: "ender-lilies",
    title: "Ender Lilies: Quietus of the Knights",
    genre: "Metroidvania",
    tags: ["metroidvania", "dark", "atmospheric", "beautiful", "action", "boss", "exploration", "rain", "melancholy", "soulslike", "anime"],
    description: "A melancholy action-RPG metroidvania set in a kingdom drowned in endless rain. Summon fallen knights as allies and explore ruins filled with sorrowful beauty.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Console"],
    popularity: "indie classic",
  },
  {
    id: "ori-blind-forest",
    title: "Ori and the Blind Forest",
    genre: "Metroidvania",
    tags: ["metroidvania", "beautiful", "emotional", "precision", "platformer", "atmospheric", "story", "nature", "forest", "colorful", "challenging"],
    description: "A visually stunning precision platformer about a guardian spirit restoring a dying forest. Fluid movement, emotional storytelling, and breathtaking art direction.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows", "Mac", "Console"],
    popularity: "indie classic",
  },
  {
    id: "ori-will-of-the-wisps",
    title: "Ori and the Will of the Wisps",
    genre: "Metroidvania",
    tags: ["metroidvania", "beautiful", "emotional", "precision", "platformer", "atmospheric", "story", "nature", "sequel", "fluid", "colorful"],
    description: "The stunning sequel to Ori and the Blind Forest. Larger world, deeper combat, and an even more emotional story about belonging and sacrifice.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows", "Console"],
    popularity: "indie classic",
  },
  {
    id: "axiom-verge",
    title: "Axiom Verge",
    genre: "Metroidvania",
    tags: ["metroidvania", "sci-fi", "retro", "exploration", "glitch", "alien", "pixel-art", "mystery", "solo-dev", "action"],
    description: "A retro sci-fi metroidvania made entirely by one developer. Uncover a mysterious alien world using a huge arsenal of weapons and glitch-exploiting tools.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Mac", "Linux", "Console"],
    popularity: "indie classic",
  },
  {
    id: "bloodstained",
    title: "Bloodstained: Ritual of the Night",
    genre: "Metroidvania",
    tags: ["metroidvania", "gothic", "action-rpg", "anime", "castlevania", "exploration", "crafting", "boss", "loot", "dark-fantasy"],
    description: "A gothic metroidvania from the creator of Castlevania. Collect shards from defeated demons to gain new powers and explore a demon-infested castle.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Mac", "Linux", "Console"],
    popularity: "popular",
  },
  {
    id: "the-messenger",
    title: "The Messenger",
    genre: "Metroidvania / Platformer",
    tags: ["metroidvania", "platformer", "ninja", "retro", "action", "humor", "time-travel", "pixel-art", "fast", "twist"],
    description: "A ninja action-platformer that transforms into a full metroidvania mid-game. Sharp writing, fluid combat, and a clever story about a demon scroll and time.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows", "Mac", "Linux", "Console"],
    popularity: "indie classic",
  },
  {
    id: "tunic",
    title: "Tunic",
    genre: "Action-Adventure",
    tags: ["action-adventure", "isometric", "puzzle", "fox", "soulslike", "mystery", "exploration", "manual", "cute-dark", "discovery"],
    description: "A fox explores a ruined world and gradually uncovers a lost instruction manual. Isometric action-adventure with soulslike combat and layers of hidden secrets.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows", "Mac", "Console"],
    popularity: "indie classic",
  },
  {
    id: "deaths-door",
    title: "Death's Door",
    genre: "Action-Adventure",
    tags: ["action-adventure", "isometric", "boss-rush", "dark", "cute", "crow", "exploration", "atmospheric", "challenging", "story"],
    description: "Play as a crow reaper collecting souls for a bureaucratic afterlife. Tight isometric combat, memorable boss fights, and a quietly moving story about mortality.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows", "Console"],
    popularity: "indie classic",
  },
  {
    id: "hyper-light-drifter",
    title: "Hyper Light Drifter",
    genre: "Action RPG",
    tags: ["action-rpg", "pixel-art", "mysterious", "difficult", "exploration", "atmospheric", "sci-fi-fantasy", "boss", "fast", "challenging"],
    description: "A mysterious drifter explores a ruined world filled with ancient technology and deadly enemies. Wordless storytelling, punishing combat, and hauntingly beautiful pixel art.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows", "Mac", "Linux", "Console"],
    popularity: "indie classic",
  },

  // ── Survival / Exploration / Crafting ──────────────────────────────────────

  {
    id: "subnautica",
    title: "Subnautica",
    genre: "Survival",
    tags: ["survival", "underwater", "ocean", "exploration", "crafting", "sci-fi", "base-building", "alien", "beautiful", "terrifying", "open-world"],
    description: "Crash-land on an alien ocean world and survive entirely underwater. Build submarines, discover alien creatures, and unravel a mysterious story beneath the waves.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Mac", "Console"],
    popularity: "indie classic",
  },
  {
    id: "subnautica-below-zero",
    title: "Subnautica: Below Zero",
    genre: "Survival",
    tags: ["survival", "underwater", "ocean", "exploration", "crafting", "sci-fi", "cold", "arctic", "alien", "story", "open-world"],
    description: "Return to the alien ocean world in its frozen arctic region. New story, new creatures, and a mix of above and below-water exploration in freezing conditions.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Mac", "Console"],
    popularity: "popular",
  },
  {
    id: "the-forest",
    title: "The Forest",
    genre: "Survival Horror",
    tags: ["survival", "horror", "crafting", "open-world", "forest", "cannibals", "building", "first-person", "exploration", "multiplayer", "dark"],
    description: "Survive in a forest inhabited by cannibal mutants after a plane crash. Build shelter, craft weapons, and explore a dark underground cave system to find your son.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Console"],
    popularity: "popular",
  },
  {
    id: "sons-of-the-forest",
    title: "Sons of the Forest",
    genre: "Survival Horror",
    tags: ["survival", "horror", "crafting", "open-world", "forest", "cannibals", "building", "first-person", "multiplayer", "sequel", "dark"],
    description: "The sequel to The Forest. Search for a missing billionaire on a cannibal-infested island. More freedom, smarter AI companions, and a bigger world to build in.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows"],
    popularity: "popular",
  },
  {
    id: "valheim",
    title: "Valheim",
    genre: "Survival",
    tags: ["survival", "viking", "crafting", "open-world", "multiplayer", "building", "exploration", "boss", "mythic", "sailing", "co-op"],
    description: "A Norse mythology survival game where slain Vikings prove their worth in a procedurally generated world. Craft gear, build longhouses, sail seas, and defeat mythical bosses.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Linux"],
    popularity: "popular",
  },
  {
    id: "terraria",
    title: "Terraria",
    genre: "Sandbox Survival",
    tags: ["sandbox", "crafting", "exploration", "2d", "survival", "building", "boss", "loot", "mining", "procedural", "co-op", "replay"],
    description: "Dig, fight, explore, and build in a procedurally generated 2D world. Terraria rewards curiosity with hundreds of items, biomes, and bosses across a massive progression system.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Mac", "Linux", "Console", "Mobile"],
    popularity: "indie classic",
  },
  {
    id: "minecraft",
    title: "Minecraft",
    genre: "Sandbox Survival",
    tags: ["sandbox", "crafting", "survival", "open-world", "building", "mining", "creative", "multiplayer", "exploration", "iconic", "procedural"],
    description: "The iconic open-world sandbox game. Mine resources, craft tools, build anything you imagine, and survive nights of monsters. Virtually unlimited creative freedom.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Mac", "Linux", "Console", "Mobile"],
    popularity: "popular",
  },
  {
    id: "dont-starve",
    title: "Don't Starve",
    genre: "Survival Roguelike",
    tags: ["survival", "gothic", "roguelike", "crafting", "dark", "procedural", "difficult", "permadeath", "weird", "art-style", "sanity"],
    description: "Survive in a dark, Tim Burton-esque wilderness by crafting, foraging, and managing your sanity. Death is permanent — each run builds new knowledge in a strange and hostile world.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Mac", "Linux", "Console"],
    popularity: "indie classic",
  },
  {
    id: "raft",
    title: "Raft",
    genre: "Survival",
    tags: ["survival", "ocean", "crafting", "building", "multiplayer", "fishing", "exploration", "sharks", "co-op", "floating"],
    description: "Drift across an endless ocean on a small raft. Hook debris to expand your platform, fish for food, fend off sharks, and discover island stories as you sail.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows"],
    popularity: "popular",
  },
  {
    id: "grounded",
    title: "Grounded",
    genre: "Survival",
    tags: ["survival", "tiny", "backyard", "crafting", "base-building", "insects", "co-op", "multiplayer", "exploration", "bugs", "spiders"],
    description: "Shrunk to the size of an ant, survive in a hostile suburban backyard. Harvest grass blades for shelter, fight giant insects, and uncover why you were shrunk.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Console"],
    popularity: "popular",
  },
  {
    id: "no-mans-sky",
    title: "No Man's Sky",
    genre: "Survival Exploration",
    tags: ["space", "survival", "exploration", "crafting", "procedural", "planets", "sci-fi", "multiplayer", "base-building", "sandbox", "flying"],
    description: "Explore an infinite procedurally generated universe of alien planets. Mine resources, build bases, trade, fight space pirates, and discover strange lifeforms.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Console"],
    popularity: "popular",
  },
  {
    id: "project-zomboid",
    title: "Project Zomboid",
    genre: "Survival",
    tags: ["survival", "zombie", "isometric", "open-world", "hardcore", "crafting", "multiplayer", "permadeath", "realistic", "dark", "depression"],
    description: "The most realistic zombie survival game. Manage hunger, illness, depression, and injuries in an isometric open-world infested with thousands of undead. How will you die?",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Mac", "Linux"],
    popularity: "cult favorite",
  },
  {
    id: "green-hell",
    title: "Green Hell",
    genre: "Survival",
    tags: ["survival", "jungle", "crafting", "realistic", "difficult", "story", "first-person", "psychological", "tropical", "permadeath"],
    description: "Abandoned in the Amazon rainforest, you must survive with nothing. Craft tools from scratch, manage wounds and parasites, and confront psychological deterioration.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Console"],
    popularity: "niche",
  },
  {
    id: "core-keeper",
    title: "Core Keeper",
    genre: "Survival Sandbox",
    tags: ["survival", "mining", "dungeon", "crafting", "co-op", "multiplayer", "pixel-art", "underground", "exploration", "boss", "cozy"],
    description: "Mine, build, and fight underground in a procedurally generated cavern world. Gather resources to power an ancient Core and take on massive underground bosses.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Mac", "Linux", "Console"],
    popularity: "niche",
  },
  {
    id: "astroneer",
    title: "Astroneer",
    genre: "Survival Exploration",
    tags: ["space", "survival", "exploration", "crafting", "base-building", "planets", "co-op", "colorful", "relaxing", "sci-fi", "sandbox"],
    description: "Explore and reshape alien planets in a colorful space exploration game. Terraform terrain, build connected bases, and uncover the secrets of a solar system.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Console"],
    popularity: "popular",
  },

  // ── Horror ─────────────────────────────────────────────────────────────────

  {
    id: "amnesia-dark-descent",
    title: "Amnesia: The Dark Descent",
    genre: "Horror",
    tags: ["horror", "atmospheric", "puzzle", "dark", "first-person", "sanity", "castle", "psychological", "stealth", "no-combat", "classic"],
    description: "A helpless man stumbles through a dark castle with no memory and no weapons. Sanity deteriorates if you look at monsters — hide, solve puzzles, and flee in pure terror.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows", "Mac", "Linux"],
    popularity: "indie classic",
  },
  {
    id: "amnesia-the-bunker",
    title: "Amnesia: The Bunker",
    genre: "Horror",
    tags: ["horror", "survival", "atmospheric", "open-world", "first-person", "bunker", "ww1", "tension", "puzzle", "monster", "stealth"],
    description: "A French soldier is trapped in a WW1 bunker with a relentless monster. Open-ended survival horror where every action makes noise and draws the creature closer.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows", "Console"],
    popularity: "popular",
  },
  {
    id: "outlast",
    title: "Outlast",
    genre: "Horror",
    tags: ["horror", "first-person", "survival", "found-footage", "asylum", "dark", "stealth", "chase", "intense", "no-combat", "documentary"],
    description: "A journalist investigates an asylum overrun by deranged inmates. Armed only with a night-vision camera and limited battery, run, hide, and document the horrors within.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows", "Mac", "Linux", "Console"],
    popularity: "popular",
  },
  {
    id: "soma",
    title: "SOMA",
    genre: "Horror",
    tags: ["horror", "sci-fi", "story", "philosophical", "underwater", "first-person", "consciousness", "atmospheric", "puzzle", "existential", "dark"],
    description: "Wake up deep in an underwater research facility where machines have taken on human consciousness. A slow-burn sci-fi horror that asks profound questions about identity and survival.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows", "Mac", "Linux", "Console"],
    popularity: "indie classic",
  },
  {
    id: "little-nightmares",
    title: "Little Nightmares",
    genre: "Horror Platformer",
    tags: ["horror", "platformer", "puzzle", "dark", "atmospheric", "stealth", "short", "child", "grotesque", "creepy", "beautiful", "silent"],
    description: "A tiny girl in a yellow raincoat navigates a grotesque vessel filled with monstrous chefs and hungry guests. Atmospheric horror platformer with no combat — only fleeing.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "short",
    platforms: ["Windows", "Mac", "Linux", "Console"],
    popularity: "popular",
  },
  {
    id: "little-nightmares-2",
    title: "Little Nightmares II",
    genre: "Horror Platformer",
    tags: ["horror", "platformer", "puzzle", "dark", "atmospheric", "stealth", "co-op", "grotesque", "creepy", "beautiful", "sequel", "city"],
    description: "A boy and a girl flee through a world warped by a mysterious signal broadcast from a pale city. More environments, more terror, and a heartbreaking finale.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "short",
    platforms: ["Windows", "Mac", "Linux", "Console"],
    popularity: "popular",
  },
  {
    id: "inside",
    title: "Inside",
    genre: "Horror Platformer",
    tags: ["horror", "platformer", "dark", "story", "atmospheric", "short", "dystopian", "puzzle", "silent", "running", "disturbing"],
    description: "A boy runs through a bleak totalitarian world where something terrible is being engineered. Wordless narrative, stunning atmosphere, and a deeply unsettling final act.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "short",
    platforms: ["Windows", "Console", "Mobile"],
    popularity: "indie classic",
  },
  {
    id: "limbo",
    title: "Limbo",
    genre: "Horror Platformer",
    tags: ["horror", "puzzle", "platformer", "black-and-white", "atmospheric", "dark", "short", "silent", "creepy", "physics", "spider"],
    description: "A boy ventures into a dark black-and-white limbo to find his missing sister. Minimalist puzzle-platformer drenched in dread and filled with brutal, inventive traps.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "short",
    platforms: ["Windows", "Mac", "Linux", "Console", "Mobile"],
    popularity: "indie classic",
  },
  {
    id: "signalis",
    title: "Signalis",
    genre: "Horror",
    tags: ["horror", "sci-fi", "pixel-art", "psychological", "survival", "puzzle", "dark", "love", "mystery", "inventory", "retro", "disturbing"],
    description: "A replika android searches for her missing partner in a frozen, nightmarish facility. Retro survival horror fusing classic Resident Evil mechanics with dreamlike sci-fi horror.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows", "Mac", "Linux", "Console"],
    popularity: "cult favorite",
  },
  {
    id: "darkwood",
    title: "Darkwood",
    genre: "Horror",
    tags: ["horror", "top-down", "survival", "atmospheric", "dark", "forest", "crafting", "stealth", "night", "psychological", "disturbing"],
    description: "Survive in a horrifying dark forest from a top-down perspective. Fortify your hideout each night, scavenge supplies by day, and face monsters that get worse the longer you stay.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows", "Mac", "Linux", "Console"],
    popularity: "cult favorite",
  },
  {
    id: "fnaf",
    title: "Five Nights at Freddy's",
    genre: "Horror",
    tags: ["horror", "short", "strategy", "jump-scares", "animatronic", "security", "tense", "cheap", "night-shift", "paranoia", "survival"],
    description: "Work as a night-shift guard in a haunted pizza restaurant. Monitor cameras, manage power, and survive attacks by possessed animatronic animals. Short, intense, iconic.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "short",
    platforms: ["Windows", "Mobile", "Console"],
    popularity: "popular",
  },
  {
    id: "doki-doki",
    title: "Doki Doki Literature Club",
    genre: "Horror Visual Novel",
    tags: ["horror", "visual-novel", "psychological", "twist", "meta", "free", "dark", "dating-sim", "disturbing", "subversive", "short"],
    description: "A seemingly cheerful visual novel dating sim that violently deconstructs itself into something deeply disturbing. Free to play — go in blind for maximum impact.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows", "Mac", "Linux"],
    popularity: "indie classic",
  },
  {
    id: "slender",
    title: "Slender: The Eight Pages",
    genre: "Horror",
    tags: ["horror", "short", "atmospheric", "walking-sim", "forest", "night", "free", "pages", "tension", "minimalist", "creepy"],
    description: "Collect eight pages scattered through a dark forest while something follows you. A free, minimalist horror experience that defined a generation of horror games.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "short",
    platforms: ["Windows", "Mac"],
    popularity: "cult favorite",
  },
  {
    id: "re2-remake",
    title: "Resident Evil 2 (Remake)",
    genre: "Survival Horror",
    tags: ["horror", "survival", "action", "third-person", "zombie", "puzzle", "inventory", "tense", "remake", "police-station", "dark"],
    description: "The modern remake of the survival horror classic. Navigate a zombie-infested police station as Leon or Claire while the relentless Tyrant hunts you room to room.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows", "Console"],
    popularity: "popular",
  },
  {
    id: "dead-space",
    title: "Dead Space",
    genre: "Survival Horror",
    tags: ["horror", "sci-fi", "survival", "action", "third-person", "space", "necromorphs", "dismemberment", "dark", "atmospheric", "intense"],
    description: "An engineer responds to a distress call on a derelict mining ship now overrun with grotesque alien monsters. Strategic dismemberment combat in a masterpiece of atmospheric sci-fi horror.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows", "Console"],
    popularity: "popular",
  },

  // ── Roguelike / Roguelite / Deckbuilding ───────────────────────────────────

  {
    id: "slay-the-spire",
    title: "Slay the Spire",
    genre: "Roguelike Deckbuilder",
    tags: ["roguelike", "deckbuilding", "strategy", "turn-based", "cards", "procedural", "difficult", "addictive", "climb", "relics", "replay"],
    description: "Craft a unique deck of cards, acquire powerful relics, and ascend an ever-changing spire. The definitive roguelike deckbuilder that spawned an entire genre.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Mac", "Linux", "Console", "Mobile"],
    popularity: "indie classic",
  },
  {
    id: "hades",
    title: "Hades",
    genre: "Roguelite",
    tags: ["roguelite", "action", "story", "mythology", "fast-paced", "difficult", "build", "boons", "narrative", "replay", "greek", "addictive"],
    description: "Escape the Underworld in this exceptional action-roguelite. The narrative evolves with every run as you fight through Hades with blessings from Olympian gods.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Mac", "Linux", "Console"],
    popularity: "indie classic",
  },
  {
    id: "hades-2",
    title: "Hades II",
    genre: "Roguelite",
    tags: ["roguelite", "action", "story", "mythology", "fast-paced", "difficult", "build", "boons", "narrative", "replay", "greek", "sequel"],
    description: "Play as Melinoë, the immortal Princess of the Underworld, fighting through new mythological locations. Bigger, deeper, and more ambitious than the original.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Mac"],
    popularity: "popular",
  },
  {
    id: "binding-of-isaac",
    title: "The Binding of Isaac: Rebirth",
    genre: "Roguelike Shooter",
    tags: ["roguelike", "dark", "shooter", "procedural", "twin-stick", "biblical", "weird", "difficult", "item-synergy", "top-down", "disturbing"],
    description: "Descend into a procedurally generated basement and fight grotesque monsters using Isaac's tears. Thousands of item combinations create wildly different runs each time.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Mac", "Linux", "Console"],
    popularity: "indie classic",
  },
  {
    id: "enter-the-gungeon",
    title: "Enter the Gungeon",
    genre: "Roguelite Shooter",
    tags: ["roguelite", "shooter", "bullet-hell", "procedural", "guns", "top-down", "difficult", "dodge-roll", "co-op", "replay", "chaotic"],
    description: "A bullet-hell dungeon crawler where every item is a gun or gun-adjacent. Dodge thousands of bullets, find legendary weapons, and reach the bottom of a living dungeon.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Mac", "Linux", "Console"],
    popularity: "indie classic",
  },
  {
    id: "risk-of-rain-2",
    title: "Risk of Rain 2",
    genre: "Roguelite",
    tags: ["roguelite", "third-person", "fast-paced", "multiplayer", "co-op", "items", "chaotic", "aliens", "boss", "run-based", "scaling"],
    description: "A third-person roguelite where you crash on an alien planet and fight escalating hordes. Stack hundreds of items per run for increasingly chaotic and overpowered results.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Console"],
    popularity: "indie classic",
  },
  {
    id: "balatro",
    title: "Balatro",
    genre: "Roguelike Deckbuilder",
    tags: ["roguelike", "deckbuilding", "poker", "addictive", "strategy", "cards", "jokers", "math", "build", "chips", "multiplier", "relaxing"],
    description: "A poker-based roguelike deckbuilder where the rules bend and break. Combine joker cards to create absurd score multipliers and win increasingly difficult hands.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Mac", "Linux", "Console", "Mobile"],
    popularity: "popular",
  },
  {
    id: "vampire-survivors",
    title: "Vampire Survivors",
    genre: "Roguelite",
    tags: ["roguelite", "survival", "bullet-hell", "auto-shooter", "upgrade", "pixel-art", "cheap", "addictive", "horde", "run-based", "idle"],
    description: "Survive waves of monsters using auto-attacking weapons that evolve with upgrades. A deeply addictive roguelite loop with minimal input and maximum chaos.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows", "Mac", "Linux", "Console", "Mobile"],
    popularity: "indie classic",
  },
  {
    id: "inscryption",
    title: "Inscryption",
    genre: "Roguelike Deckbuilder",
    tags: ["roguelike", "deckbuilding", "horror", "puzzle", "meta", "escape-room", "cards", "dark", "mystery", "subversive", "unique"],
    description: "A deckbuilder trapped in a dark cabin escape-room that is not what it appears to be. Deeply subversive — the less you know going in, the better.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows", "Mac", "Linux", "Console"],
    popularity: "indie classic",
  },
  {
    id: "ftl",
    title: "FTL: Faster Than Light",
    genre: "Roguelike Strategy",
    tags: ["roguelike", "strategy", "space", "real-time", "ship", "crew", "difficult", "procedural", "sci-fi", "permadeath", "management"],
    description: "Captain a spaceship across a hostile galaxy in this real-time roguelike. Manage crew, upgrade systems, and make life-or-death decisions in randomly generated star sectors.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows", "Mac", "Linux"],
    popularity: "indie classic",
  },
  {
    id: "into-the-breach",
    title: "Into the Breach",
    genre: "Roguelike Strategy",
    tags: ["roguelike", "strategy", "turn-based", "mechs", "chess-like", "puzzle", "sci-fi", "procedural", "tactical", "minimalist", "replay"],
    description: "Pilot mechs to defend cities from alien kaiju in this precise, chess-like turn-based strategy roguelike. Every move is a puzzle with a knowable solution.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows", "Mac", "Linux", "Console"],
    popularity: "indie classic",
  },
  {
    id: "darkest-dungeon",
    title: "Darkest Dungeon",
    genre: "Roguelike RPG",
    tags: ["roguelike", "dark", "rpg", "difficult", "management", "stress", "gothic", "turn-based", "permadeath", "party", "horror", "brutal"],
    description: "Recruit and manage a party of flawed heroes delving into gothic, Lovecraftian dungeons. Manage stress, afflictions, and death as your roster slowly degrades.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Mac", "Linux", "Console", "Mobile"],
    popularity: "indie classic",
  },
  {
    id: "rogue-legacy-2",
    title: "Rogue Legacy 2",
    genre: "Roguelite Platformer",
    tags: ["roguelite", "platformer", "action", "procedural", "inheritance", "rpg", "boss", "classes", "castle", "upgrade", "pixel-art"],
    description: "Fight through a randomized castle as a lineage of quirky heirs, each with unique traits and classes. Every death funds upgrades for your next descendant in a polished sequel.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Mac", "Linux", "Console"],
    popularity: "popular",
  },
  {
    id: "spelunky-2",
    title: "Spelunky 2",
    genre: "Roguelike Platformer",
    tags: ["roguelike", "platformer", "difficult", "exploration", "procedural", "permadeath", "mining", "traps", "pixel-art", "secrets", "mastery"],
    description: "Explore procedurally generated cave systems in this brutally difficult roguelike platformer. Every death teaches you something — mastery here feels genuinely earned.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Console"],
    popularity: "indie classic",
  },
  {
    id: "noita",
    title: "Noita",
    genre: "Roguelike",
    tags: ["roguelike", "physics", "magic", "wand-crafting", "difficult", "procedural", "pixel-physics", "sandbox", "secrets", "deep", "weird"],
    description: "Every pixel is simulated in this physics-based roguelike. Craft wands with spell combinations, discover massive secrets, and die in spectacular and unexpected ways.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows"],
    popularity: "cult favorite",
  },

  // ── Platformer / Precision ─────────────────────────────────────────────────

  {
    id: "celeste",
    title: "Celeste",
    genre: "Precision Platformer",
    tags: ["platformer", "difficult", "emotional", "precision", "story", "mental-health", "tight-controls", "hard", "beautiful", "pixel-art", "assist-mode"],
    description: "Climb a mountain as Madeline in this emotionally resonant precision platformer. Tight controls, brutally demanding levels, and an honest story about anxiety and perseverance.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows", "Mac", "Linux", "Console"],
    popularity: "indie classic",
  },
  {
    id: "super-meat-boy",
    title: "Super Meat Boy",
    genre: "Precision Platformer",
    tags: ["platformer", "ultra-hard", "precision", "fast", "difficult", "saw-blades", "retro", "tight", "replay", "short-levels"],
    description: "Race through brutal stages packed with saw blades and deadly traps to save Bandage Girl. Ultra-tight controls and instant respawning make failing into learning.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows", "Mac", "Linux", "Console"],
    popularity: "indie classic",
  },
  {
    id: "cuphead",
    title: "Cuphead",
    genre: "Platformer Boss Rush",
    tags: ["platformer", "boss-rush", "difficult", "cartoon", "retro", "1930s", "animation", "run-and-gun", "beautiful", "hard", "co-op"],
    description: "A 1930s cartoon-style run-and-gun game focused almost entirely on boss fights. Gorgeous hand-drawn animation and punishing difficulty that demands perfection.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows", "Mac", "Console"],
    popularity: "indie classic",
  },
  {
    id: "pizza-tower",
    title: "Pizza Tower",
    genre: "Platformer",
    tags: ["platformer", "fast", "absurd", "combo", "wario-like", "pizza", "momentum", "rank", "pixel-art", "chaotic", "funny"],
    description: "A pizza chef sprints through his tower to stop it from being destroyed. Momentum-based platforming rewarded by combo rankings — frenetic, absurd, and brilliantly designed.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows"],
    popularity: "indie classic",
  },
  {
    id: "shovel-knight",
    title: "Shovel Knight",
    genre: "Platformer",
    tags: ["platformer", "retro", "action", "pixel-art", "nes-style", "knight", "digging", "boss", "collectibles", "classic"],
    description: "A heroic knight wielding a shovel quests to save his companion. A love letter to NES-era platformers with tight controls, great boss fights, and enormous content.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows", "Mac", "Linux", "Console"],
    popularity: "indie classic",
  },
  {
    id: "geometry-dash",
    title: "Geometry Dash",
    genre: "Rhythm Platformer",
    tags: ["platformer", "rhythm", "music", "precise", "auto-runner", "difficult", "community", "levels", "timing", "arcade", "twitchy"],
    description: "Tap to the beat through obstacle-filled levels in this precision rhythm platformer. Huge community of custom levels and an iconic soundtrack make runs endlessly replayable.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Mac", "Mobile"],
    popularity: "popular",
  },
  {
    id: "a-hat-in-time",
    title: "A Hat in Time",
    genre: "3D Platformer",
    tags: ["3d-platformer", "cute", "adventure", "collect-a-thon", "hats", "time-pieces", "colorful", "funny", "wholesome", "mario-like", "co-op"],
    description: "A little girl called Hat Kid collects hourglasses across whimsical worlds in this joyful 3D collect-a-thon. Tight platforming, funny writing, and huge community mods.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows", "Mac", "Console"],
    popularity: "indie classic",
  },
  {
    id: "rayman-legends",
    title: "Rayman Legends",
    genre: "Platformer",
    tags: ["platformer", "co-op", "beautiful", "music", "colorful", "humor", "art", "challenging", "musical-levels", "rhythm", "multiplayer"],
    description: "One of the most polished platformers ever made. Gorgeous art, tight controls, hilarious co-op, and legendary music levels synced perfectly to rock covers.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows", "Console"],
    popularity: "indie classic",
  },
  {
    id: "katana-zero",
    title: "Katana ZERO",
    genre: "Action Platformer",
    tags: ["action", "platformer", "neo-noir", "one-hit-kill", "katana", "slow-motion", "story", "samurai", "synth", "brutal", "fast"],
    description: "A samurai assassin with a time-manipulation drug navigates a neo-noir city. Every hit kills — plan each corridor using slow-motion and precise sword strikes.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "short",
    platforms: ["Windows", "Console"],
    popularity: "indie classic",
  },
  {
    id: "sanabi",
    title: "SANABI",
    genre: "Action Platformer",
    tags: ["action", "platformer", "grappling-hook", "story", "neo-noir", "cyberpunk", "fast", "parkour", "emotional", "daughter", "pixel-art"],
    description: "A retired veteran with a chain arm grapples through a dystopian cyberpunk megacity to find a girl. A touching story wrapped in fast, stylish grapple-based platforming.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows", "Console"],
    popularity: "niche",
  },

  // ── FPS / Shooter ──────────────────────────────────────────────────────────

  {
    id: "krunker",
    title: "Krunker",
    genre: "FPS",
    tags: ["fps", "browser", "fast", "competitive", "free", "online", "arena", "pixel-art", "multiplayer", "quick", "lightweight"],
    description: "A fast-paced browser-based FPS with minimal download requirements. Multiple classes, custom maps, and a surprisingly deep competitive scene — playable instantly.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Browser", "Windows"],
    popularity: "popular",
  },
  {
    id: "xonotic",
    title: "Xonotic",
    genre: "Arena FPS",
    tags: ["fps", "arena", "fast", "free", "open-source", "multiplayer", "competitive", "bunny-hop", "rockets", "quake-like"],
    description: "A free, open-source arena FPS inspired by Quake. Fast movement, projectile-based weapons, and active competitive community — no pay-to-win, ever.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Mac", "Linux"],
    popularity: "niche",
  },
  {
    id: "ultrakill",
    title: "Ultrakill",
    genre: "FPS",
    tags: ["fps", "fast", "stylish", "retro", "difficult", "hell", "parry", "style-rank", "arcade", "blood", "coin", "movement"],
    description: "A machine drains blood from demons in Hell to refuel. Extraordinarily fast retro FPS with a style-ranking system rewarding aggressive, creative combat.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows"],
    popularity: "cult favorite",
  },
  {
    id: "dusk",
    title: "DUSK",
    genre: "FPS",
    tags: ["fps", "retro", "dark", "fast", "horror", "occult", "quake-like", "brutal", "movement", "difficult", "atmosphere"],
    description: "A brutal retro FPS set in rural occult nightmare landscapes. Inspired by Quake and Blood, it delivers some of the best boomer-shooter movement and level design available.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows", "Mac", "Linux", "Console"],
    popularity: "cult favorite",
  },
  {
    id: "doom-eternal",
    title: "DOOM Eternal",
    genre: "FPS",
    tags: ["fps", "fast", "brutal", "demanding", "metal", "demons", "hell", "arena", "movement", "aggressive", "skill-based"],
    description: "The Doom Slayer tears through Hell at maximum speed. Demanding skill-based FPS that rewards weapon-switching, platforming, and relentless aggression with heavy metal glory.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows", "Console"],
    popularity: "popular",
  },
  {
    id: "quake",
    title: "Quake",
    genre: "Arena FPS",
    tags: ["fps", "arena", "classic", "fast", "multiplayer", "dark", "gothic", "rockets", "bunny-hop", "deathmatch", "iconic"],
    description: "The original arena FPS that defined competitive multiplayer shooting. Dark gothic single-player campaign plus lightning-fast deathmatch modes that still hold up perfectly.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows", "Mac", "Linux", "Console"],
    popularity: "indie classic",
  },
  {
    id: "tf2",
    title: "Team Fortress 2",
    genre: "FPS",
    tags: ["fps", "team", "class-based", "multiplayer", "free", "hats", "casual", "competitive", "humor", "cartoon", "iconic"],
    description: "A team-based class shooter with distinct characters, exaggerated humor, and enormous depth. Free-to-play with a robust hat economy — still wildly popular after nearly 20 years.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Mac", "Linux"],
    popularity: "popular",
  },
  {
    id: "cs2",
    title: "Counter-Strike 2",
    genre: "Tactical FPS",
    tags: ["fps", "tactical", "competitive", "multiplayer", "bomb", "team", "ranked", "skill-based", "free", "esports", "precision"],
    description: "The definitive competitive tactical FPS. Buy weapons, plant or defuse bombs, and coordinate with teammates in tight 5v5 rounds demanding precise aim and strategy.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows"],
    popularity: "popular",
  },
  {
    id: "valorant",
    title: "Valorant",
    genre: "Tactical FPS",
    tags: ["fps", "tactical", "abilities", "competitive", "multiplayer", "ranked", "free", "esports", "team", "agents", "skill-based"],
    description: "A tactical FPS blending precise gunplay with unique agent abilities. Five-versus-five bomb-planting gameplay with a massive competitive ranked mode.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows"],
    popularity: "popular",
  },
  {
    id: "apex-legends",
    title: "Apex Legends",
    genre: "Battle Royale FPS",
    tags: ["fps", "battle-royale", "abilities", "free", "multiplayer", "team", "movement", "legends", "ping-system", "fast", "competitive"],
    description: "A squad-based battle royale FPS with fluid movement and unique legend abilities. Drop onto an island, loot, and be the last squad standing with slick gunplay.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Console"],
    popularity: "popular",
  },
  {
    id: "titanfall-2",
    title: "Titanfall 2",
    genre: "FPS",
    tags: ["fps", "fast", "mech", "parkour", "story", "movement", "titans", "campaign", "multiplayer", "wall-running", "fluid"],
    description: "A pilot and their titan robot must escape a hostile planet. Features one of the best single-player FPS campaigns ever made plus an intensely fluid multiplayer mode.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows", "Console"],
    popularity: "cult favorite",
  },
  {
    id: "borderlands-2",
    title: "Borderlands 2",
    genre: "Looter Shooter",
    tags: ["fps", "loot-shooter", "rpg", "co-op", "humor", "guns", "open-world", "classes", "story", "multiplayer", "cell-shaded"],
    description: "Shoot billions of procedurally generated guns while raiding Pandora's vaults. Co-op looting and an iconic villain make this cel-shaded RPG-shooter a timeless classic.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Mac", "Linux", "Console"],
    popularity: "indie classic",
  },
  {
    id: "deep-rock-galactic",
    title: "Deep Rock Galactic",
    genre: "Co-op FPS",
    tags: ["fps", "co-op", "mining", "aliens", "teamwork", "multiplayer", "underground", "procedural", "dwarves", "fun", "classes"],
    description: "A team of space-dwarves mines dangerous caves full of alien bugs. Procedurally generated underground missions demand tight teamwork and generous camaraderie.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Console"],
    popularity: "indie classic",
  },

  // ── Cozy / Farming / Life Sim ──────────────────────────────────────────────

  {
    id: "stardew-valley",
    title: "Stardew Valley",
    genre: "Farming Sim",
    tags: ["farming", "cozy", "life-sim", "rpg", "relaxing", "crafting", "fishing", "mining", "relationships", "solo-dev", "multiplayer"],
    description: "Rebuild your grandfather's farm in a charming valley full of secrets and friendly townsfolk. Mine, fish, farm, and forge relationships at your own peaceful pace.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Mac", "Linux", "Console", "Mobile"],
    popularity: "indie classic",
  },
  {
    id: "animal-crossing",
    title: "Animal Crossing: New Horizons",
    genre: "Life Sim",
    tags: ["life-sim", "cozy", "creative", "multiplayer", "relaxing", "island", "decorating", "social", "cute", "animals", "daily"],
    description: "Build and decorate your dream island community with adorable animal villagers. No pressure gameplay changes by the real clock, encouraging daily peaceful visits.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Console"],
    popularity: "popular",
  },
  {
    id: "spiritfarer",
    title: "Spiritfarer",
    genre: "Management Adventure",
    tags: ["cozy", "management", "emotional", "story", "death", "crafting", "boat", "building", "relaxing", "grief", "wholesome"],
    description: "Play as a ferrymaster to the dead, building a comfortable vessel for spirits before they pass on. A deeply emotional management game about grief, letting go, and care.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Mac", "Linux", "Console"],
    popularity: "indie classic",
  },
  {
    id: "slime-rancher",
    title: "Slime Rancher",
    genre: "Adventure Farming",
    tags: ["cozy", "adventure", "cute", "exploration", "collect", "farm", "slimes", "colorful", "relaxing", "open-world", "first-person"],
    description: "Ranch adorable slimes on an alien planet by shooting and feeding them. A cheerful, stress-free farming adventure with surprising depth as you expand your ranch.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows", "Mac", "Console"],
    popularity: "popular",
  },
  {
    id: "slime-rancher-2",
    title: "Slime Rancher 2",
    genre: "Adventure Farming",
    tags: ["cozy", "adventure", "cute", "exploration", "collect", "farm", "slimes", "colorful", "relaxing", "sequel", "first-person"],
    description: "Beatrix returns to a new rainbow island filled with new slimes and biomes. Bigger, prettier, and with fresh conservation and exploration mechanics.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows", "Console"],
    popularity: "popular",
  },
  {
    id: "a-short-hike",
    title: "A Short Hike",
    genre: "Adventure",
    tags: ["cozy", "adventure", "short", "exploration", "cute", "hiking", "mountains", "relaxing", "wholesome", "walking", "birds"],
    description: "A tiny bird hikes to the top of a mountain. A two-hour cozy adventure with optional sidequests, gentle conversations, and beautiful voxel scenery.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "short",
    platforms: ["Windows", "Mac", "Linux", "Console"],
    popularity: "indie classic",
  },
  {
    id: "unpacking",
    title: "Unpacking",
    genre: "Puzzle",
    tags: ["cozy", "puzzle", "story", "zen", "relaxing", "moving", "home", "spatial", "narrative", "short", "satisfying"],
    description: "Unpack boxes and arrange belongings across eight life moves, telling a wordless story through what someone owns. A warm, meditative spatial puzzle about growing up.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "short",
    platforms: ["Windows", "Mac", "Linux", "Console"],
    popularity: "indie classic",
  },
  {
    id: "dave-the-diver",
    title: "Dave the Diver",
    genre: "Adventure Management",
    tags: ["cozy", "adventure", "sushi", "management", "ocean", "diving", "fishing", "story", "humor", "boss", "unique"],
    description: "Dive an ever-changing blue hole by day and run a sushi restaurant by night. Surprisingly deep blend of adventure, management, fishing, and boss fights.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows", "Mac", "Console"],
    popularity: "indie classic",
  },
  {
    id: "dredge",
    title: "Dredge",
    genre: "Fishing Horror",
    tags: ["cozy", "horror", "fishing", "atmospheric", "story", "dark", "ocean", "lovecraftian", "management", "boat", "night"],
    description: "A fisherman discovers unspeakable things lurking beneath a remote archipelago. Cozy fishing by day turns into creeping dread by night in this Lovecraftian management game.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows", "Mac", "Linux", "Console"],
    popularity: "indie classic",
  },
  {
    id: "my-time-at-portia",
    title: "My Time at Portia",
    genre: "Life Sim",
    tags: ["life-sim", "farming", "crafting", "rpg", "cozy", "post-apocalyptic", "building", "relationships", "exploration", "workshop"],
    description: "Rebuild a workshop in a charming post-apocalyptic town, craft machines, and forge friendships. A rich life-sim with deep crafting trees and a vibrant community to explore.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Mac", "Console"],
    popularity: "niche",
  },
  {
    id: "my-time-at-sandrock",
    title: "My Time at Sandrock",
    genre: "Life Sim",
    tags: ["life-sim", "farming", "crafting", "rpg", "cozy", "desert", "building", "relationships", "exploration", "sequel"],
    description: "Run a workshop in a desert community in the sequel to Portia. Bigger world, improved systems, and a lively cast of characters to befriend and help rebuild a desert town.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Console"],
    popularity: "niche",
  },
  {
    id: "coral-island",
    title: "Coral Island",
    genre: "Farming Sim",
    tags: ["farming", "cozy", "life-sim", "colorful", "diving", "ocean", "relationships", "indie", "crafting", "community", "relaxing"],
    description: "Farm, dive, and restore a tropical island in this lush cozy life-sim. Large cast of diverse characters to befriend, an ocean ecosystem to clean, and a town to rebuild.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Console"],
    popularity: "niche",
  },
  {
    id: "moonlighter",
    title: "Moonlighter",
    genre: "Action Roguelite",
    tags: ["action", "roguelite", "shop-management", "exploration", "dungeon", "pixel-art", "crafting", "merchant", "indie", "run-based"],
    description: "A merchant dreams of being a hero. Explore procedural dungeons by night and manage your shop by day — pricing items, managing inventory, and crafting better gear.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows", "Mac", "Linux", "Console"],
    popularity: "niche",
  },

  // ── Puzzle / Story / Adventure ─────────────────────────────────────────────

  {
    id: "portal",
    title: "Portal",
    genre: "Puzzle",
    tags: ["puzzle", "first-person", "portal-gun", "clever", "short", "physics", "humor", "ai", "test-chamber", "sci-fi", "iconic"],
    description: "A mute test subject solves physics puzzles using a gun that creates linked portals. Brilliantly designed spatial puzzles and one of gaming's most iconic antagonists.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "short",
    platforms: ["Windows", "Mac", "Linux", "Console"],
    popularity: "indie classic",
  },
  {
    id: "portal-2",
    title: "Portal 2",
    genre: "Puzzle",
    tags: ["puzzle", "co-op", "story", "first-person", "portal-gun", "clever", "humor", "physics", "ai", "multiplayer", "sequel"],
    description: "Bigger, funnier, and even more cleverly designed than the original. A rich single-player story plus a remarkable co-op campaign where two portals become four.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows", "Mac", "Linux", "Console"],
    popularity: "indie classic",
  },
  {
    id: "the-witness",
    title: "The Witness",
    genre: "Puzzle",
    tags: ["puzzle", "open-world", "silent", "discovery", "difficult", "island", "panel", "nature", "observation", "philosophical", "secretive"],
    description: "Explore a mysterious island filled with hundreds of panel puzzles that must be understood, not just solved. A demanding, beautiful puzzle game about observation and insight.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Mac", "Console"],
    popularity: "cult favorite",
  },
  {
    id: "outer-wilds",
    title: "Outer Wilds",
    genre: "Exploration Adventure",
    tags: ["exploration", "mystery", "sci-fi", "time-loop", "wonder", "space", "discovery", "story", "short", "emotional", "no-combat"],
    description: "Explore a solar system trapped in a 22-minute time loop. A masterpiece of discovery-driven design where knowledge, not upgrades, drives progress through a stunning space mystery.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows", "Mac", "Console"],
    popularity: "indie classic",
  },
  {
    id: "obra-dinn",
    title: "Return of the Obra Dinn",
    genre: "Mystery Puzzle",
    tags: ["mystery", "logic", "historical", "detective", "unique", "ship", "puzzle", "deduction", "1-bit", "short", "atmospheric"],
    description: "An insurance investigator boards a ghost ship to determine the fate of all 60 crew members. Pure deduction puzzle with a striking 1-bit art style and unforgettable design.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows", "Mac", "Linux", "Console"],
    popularity: "indie classic",
  },
  {
    id: "firewatch",
    title: "Firewatch",
    genre: "Walking Sim",
    tags: ["walking-sim", "story", "nature", "mystery", "atmospheric", "hiking", "forest", "dialogue", "short", "relaxing", "relationship"],
    description: "A fire lookout's quiet Wyoming summer turns mysterious. A beautiful narrative walking-sim about solitude, connection, and what we run from — told through crackling radio dialogue.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "short",
    platforms: ["Windows", "Mac", "Linux", "Console"],
    popularity: "indie classic",
  },
  {
    id: "edith-finch",
    title: "What Remains of Edith Finch",
    genre: "Walking Sim",
    tags: ["walking-sim", "story", "emotional", "short", "family", "death", "narrative", "anthology", "beautiful", "wonder", "vignettes"],
    description: "Explore the abandoned Finch family house and discover how each peculiar family member died. Short, stunning narrative vignettes that rank among gaming's most affecting moments.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "short",
    platforms: ["Windows", "Console"],
    popularity: "indie classic",
  },
  {
    id: "undertale",
    title: "Undertale",
    genre: "RPG",
    tags: ["rpg", "story", "pixel-art", "emotional", "pacifist", "bullet-hell", "humor", "twist", "music", "meta", "indie", "unique"],
    description: "A human child falls underground into a world of monsters. An RPG where you can befriend every enemy instead of fighting — with wildly different outcomes based on your choices.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows", "Mac", "Linux", "Console"],
    popularity: "indie classic",
  },
  {
    id: "disco-elysium",
    title: "Disco Elysium",
    genre: "RPG",
    tags: ["rpg", "detective", "story", "political", "weird", "dialogue", "skill-checks", "text-heavy", "deep", "unique", "adult"],
    description: "An amnesiac detective reconstructs himself and solves a murder in a crumbling port city. A dialogue-driven RPG of staggering depth, politics, and existential weirdness.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "long",
    platforms: ["Windows", "Mac", "Linux", "Console"],
    popularity: "indie classic",
  },
  {
    id: "papers-please",
    title: "Papers, Please",
    genre: "Puzzle",
    tags: ["puzzle", "dystopian", "story", "management", "moral", "immigration", "inspection", "short", "oppressive", "unique", "memorable"],
    description: "Inspect documents as an immigration officer in a Soviet-style dystopia. Every decision carries moral weight — follow orders or help people at risk of your family's wellbeing.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows", "Mac", "Linux", "Mobile"],
    popularity: "indie classic",
  },
  {
    id: "stanley-parable",
    title: "The Stanley Parable",
    genre: "Walking Sim",
    tags: ["walking-sim", "meta", "humor", "choices", "short", "narrator", "comedy", "fourth-wall", "experimental", "office", "unique"],
    description: "Follow or disobey a narrator's instructions in an office building. A brilliant, endlessly funny meditation on free will, games, and storytelling with dozens of endings.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "short",
    platforms: ["Windows", "Mac", "Linux", "Console"],
    popularity: "indie classic",
  },
  {
    id: "night-in-the-woods",
    title: "Night in the Woods",
    genre: "Adventure",
    tags: ["adventure", "story", "emotional", "college", "cats", "small-town", "platformer", "dialogue", "friendship", "anxiety", "indie"],
    description: "A college dropout cat returns to her dying small town. A resonant story-adventure about young adulthood, belonging, and mental health told through vivid characters.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "medium",
    platforms: ["Windows", "Mac", "Linux", "Console"],
    popularity: "indie classic",
  },
  {
    id: "gris",
    title: "GRIS",
    genre: "Platformer",
    tags: ["platformer", "beautiful", "emotional", "art", "wordless", "watercolor", "short", "grief", "music", "atmospheric", "peaceful"],
    description: "A young woman traverses a crumbling world in a journey of grief and growth. A breathtaking watercolor platformer with no death, no combat — just beauty and feeling.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "short",
    platforms: ["Windows", "Mac", "Linux", "Console", "Mobile"],
    popularity: "indie classic",
  },
  {
    id: "journey",
    title: "Journey",
    genre: "Adventure",
    tags: ["adventure", "co-op", "beautiful", "short", "wordless", "mysterious", "sand", "ruins", "emotional", "online", "meditation"],
    description: "A robed traveler makes their way to a distant mountain. A wordless co-op adventure where you may encounter a stranger to travel with — and part without ever speaking.",
    novariteAvailable: false,
    novariteNote: "Reference recommendation only",
    length: "short",
    platforms: ["Windows", "Console"],
    popularity: "indie classic",
  },
];

// Build a rich text string per game used by QVAC embeddings and fallback matching.
export function gameToText(game) {
  const novariteHint = game.novariteAvailable ? "Available on Novarite platform. Download or buy now." : "";
  return `${game.title} — ${game.genre}. Tags: ${game.tags.join(", ")}. ${game.description} ${novariteHint}`.trim();
}

// Cosine similarity: dot product divided by the product of L2 norms. Range [-1, 1].
export function cosineSimilarity(a, b) {
  let dot = 0, normA = 0, normB = 0;
  for (let i = 0; i < a.length; i++) {
    dot   += a[i] * b[i];
    normA += a[i] * a[i];
    normB += b[i] * b[i];
  }
  return dot / (Math.sqrt(normA) * Math.sqrt(normB));
}

// Explain a recommendation by surfacing tags that overlap with the query.
export function buildReason(game, query) {
  const q = query.toLowerCase();
  const matched = game.tags.filter((t) => q.includes(t));
  if (matched.length > 0) return `Matched on: ${matched.join(", ")}`;
  return `${game.genre} — ${game.tags.slice(0, 3).join(", ")}`;
}
