import { NextRequest, NextResponse } from "next/server";
import { supabaseAdmin } from "@/lib/supabase/admin";

// ── Constants ──────────────────────────────────────────────────────────────

const VALID_PRICING   = new Set(["free", "paid-sol"]);
const VALID_NETWORKS  = new Set(["devnet", "testnet", "mainnet-beta"]);
const VALID_STATUSES  = new Set(["prototype", "demo", "early-access", "released"]);

const MAX_TITLE_LEN     = 120;
const MAX_SHORT_LEN     = 500;
const MAX_FULL_LEN      = 5000;
const MAX_URL_LEN       = 500;
const MAX_TAGS          = 10;
const MAX_TAG_LEN       = 30;
const MAX_BUILD_TYPES   = 10;
const MAX_ID_LEN        = 100;

// Solana base58 public key: 32 bytes → 43–44 base58 chars
const SOL_WALLET_RE    = /^[1-9A-HJ-NP-Za-km-z]{32,44}$/;
// local_game_id generated by lib/games.ts: "game_<timestamp>_<rand>"
const LOCAL_GAME_ID_RE = /^[A-Za-z0-9_-]{1,100}$/;

// ── Helpers ────────────────────────────────────────────────────────────────

function json(body: object, status = 200) {
  return NextResponse.json(body, { status });
}

function isValidUrl(url: string): boolean {
  if (url.length > MAX_URL_LEN) return false;
  return /^https?:\/\/.+/.test(url);
}

// ── Request body shape ─────────────────────────────────────────────────────

interface PublishBody {
  local_game_id:       string;
  title:               string;
  short_desc?:         string;
  description?:        string;
  engine?:             string;
  genre?:              string;
  tags?:               unknown;
  game_status?:        string;
  build_types?:        unknown;
  platform?:           string;
  download_url?:       string;
  file_size_label?:    string;
  game_version?:       string;
  pricing?:            string;
  price_sol?:          unknown;
  developer_wallet?:   string;
  developer_username?: string;
  external_play_url?:  string;
  trailer_url?:        string;
  is_published?:       unknown;
  network?:            string;
}

// ── Route handler ──────────────────────────────────────────────────────────

export async function POST(request: NextRequest) {
  // ── Authentication ─────────────────────────────────────────────────────
  const token = request.headers.get("Authorization")?.replace(/^Bearer\s+/i, "").trim();
  if (!token) {
    return json({ error: "Authentication required. Please sign in." }, 401);
  }

  const { data: { user: authUser }, error: authErr } = await supabaseAdmin.auth.getUser(token);
  if (authErr || !authUser) {
    return json({ error: "Invalid or expired session. Please sign in again." }, 401);
  }

  // Fetch the caller's verified username from the profiles table.
  // This is the authoritative value — client-supplied developer_username is ignored.
  const { data: profileData } = await supabaseAdmin
    .from("profiles")
    .select("username")
    .eq("id", authUser.id)
    .maybeSingle();
  const verifiedUsername = (profileData as { username: string } | null)?.username ?? null;

  // ── Parse body ─────────────────────────────────────────────────────────
  let body: PublishBody;
  try {
    body = await request.json() as PublishBody;
  } catch {
    return json({ error: "Request body must be valid JSON." }, 400);
  }

  // ── local_game_id ──────────────────────────────────────────────────────
  const localGameId = typeof body.local_game_id === "string"
    ? body.local_game_id.trim() : "";
  if (!localGameId)
    return json({ error: "local_game_id is required." }, 400);
  if (localGameId.length > MAX_ID_LEN || !LOCAL_GAME_ID_RE.test(localGameId))
    return json({ error: "local_game_id may only contain letters, digits, hyphens, and underscores (max 100 chars)." }, 400);

  // ── title ──────────────────────────────────────────────────────────────
  const title = typeof body.title === "string" ? body.title.trim() : "";
  if (!title)
    return json({ error: "title is required." }, 400);
  if (title.length > MAX_TITLE_LEN)
    return json({ error: `title must be ${MAX_TITLE_LEN} characters or fewer.` }, 400);

  // ── pricing ────────────────────────────────────────────────────────────
  const pricing = typeof body.pricing === "string" ? body.pricing.trim() : "free";
  if (!VALID_PRICING.has(pricing))
    return json({ error: 'pricing must be "free" or "paid-sol".' }, 400);

  // ── price_sol ──────────────────────────────────────────────────────────
  const rawPrice = body.price_sol;
  const priceSol = typeof rawPrice === "number" ? rawPrice : Number(rawPrice ?? 0);
  if (!isFinite(priceSol) || priceSol < 0)
    return json({ error: "price_sol must be a non-negative number." }, 400);
  if (pricing === "paid-sol" && priceSol <= 0)
    return json({ error: "price_sol must be greater than 0 for paid games." }, 400);

  // ── developer_wallet ───────────────────────────────────────────────────
  const developerWallet = typeof body.developer_wallet === "string"
    ? body.developer_wallet.trim() : "";
  if (pricing === "paid-sol") {
    if (!developerWallet)
      return json({ error: "developer_wallet is required for paid games." }, 400);
    if (!SOL_WALLET_RE.test(developerWallet))
      return json({ error: "developer_wallet must be a valid Solana public key (base58, 32–44 chars)." }, 400);
  }

  // ── developer_username ─────────────────────────────────────────────────
  // Always use the verified username from the authenticated user's profile.
  // The client-supplied value is ignored to prevent impersonation.
  const developerUsername = verifiedUsername;

  // ── Optional text fields ───────────────────────────────────────────────
  const shortDesc = typeof body.short_desc === "string"
    ? body.short_desc.trim() : null;
  if (shortDesc && shortDesc.length > MAX_SHORT_LEN)
    return json({ error: `short_desc must be ${MAX_SHORT_LEN} characters or fewer.` }, 400);

  const description = typeof body.description === "string"
    ? body.description.trim() : null;
  if (description && description.length > MAX_FULL_LEN)
    return json({ error: `description must be ${MAX_FULL_LEN} characters or fewer.` }, 400);

  // ── URL fields ─────────────────────────────────────────────────────────
  const downloadUrl = typeof body.download_url === "string"
    ? body.download_url.trim() : null;
  if (downloadUrl && !isValidUrl(downloadUrl))
    return json({ error: "download_url must be a valid http/https URL." }, 400);

  const externalPlayUrl = typeof body.external_play_url === "string"
    ? body.external_play_url.trim() : null;
  if (externalPlayUrl && !isValidUrl(externalPlayUrl))
    return json({ error: "external_play_url must be a valid http/https URL." }, 400);

  const trailerUrl = typeof body.trailer_url === "string"
    ? body.trailer_url.trim() : null;
  if (trailerUrl && !isValidUrl(trailerUrl))
    return json({ error: "trailer_url must be a valid http/https URL." }, 400);

  // ── game_status ────────────────────────────────────────────────────────
  const rawStatus = typeof body.game_status === "string" ? body.game_status.trim() : null;
  const gameStatus = (rawStatus && VALID_STATUSES.has(rawStatus)) ? rawStatus : null;

  // ── tags ───────────────────────────────────────────────────────────────
  const tags = Array.isArray(body.tags)
    ? (body.tags as unknown[])
        .slice(0, MAX_TAGS)
        .map((t) => String(t).trim().slice(0, MAX_TAG_LEN))
        .filter(Boolean)
    : [];

  // ── build_types ────────────────────────────────────────────────────────
  const buildTypes = Array.isArray(body.build_types)
    ? (body.build_types as unknown[])
        .slice(0, MAX_BUILD_TYPES)
        .map((t) => String(t).trim().slice(0, 30))
        .filter(Boolean)
    : [];

  // ── network ────────────────────────────────────────────────────────────
  const rawNetwork = typeof body.network === "string" ? body.network.trim() : "devnet";
  const network = VALID_NETWORKS.has(rawNetwork) ? rawNetwork : "devnet";

  // ── is_published ───────────────────────────────────────────────────────
  const isPublished = body.is_published === true || body.is_published === false
    ? Boolean(body.is_published) : true;

  // ── Assemble row ───────────────────────────────────────────────────────
  const row = {
    local_game_id:      localGameId,
    title,
    short_desc:         shortDesc,
    description,
    engine:             typeof body.engine   === "string" ? body.engine.trim().slice(0, 60)   || null : null,
    genre:              typeof body.genre    === "string" ? body.genre.trim().slice(0, 60)    || null : null,
    tags,
    game_status:        gameStatus,
    build_types:        buildTypes,
    platform:           typeof body.platform === "string" ? body.platform.trim().slice(0, 60) || null : null,
    download_url:       downloadUrl,
    file_size_label:    typeof body.file_size_label === "string" ? body.file_size_label.trim().slice(0, 30) || null : null,
    game_version:       typeof body.game_version    === "string" ? body.game_version.trim().slice(0, 30)    || null : null,
    pricing,
    price_sol:          pricing === "free" ? 0 : priceSol,
    developer_wallet:   developerWallet || null,
    developer_username: developerUsername || null,
    external_play_url:  externalPlayUrl,
    trailer_url:        trailerUrl,
    is_published:       isPublished,
    network,
    updated_at:         new Date().toISOString(),
  };

  const { data, error } = await supabaseAdmin
    .from("games")
    .upsert(row, { onConflict: "local_game_id" })
    .select("id, local_game_id")
    .single();

  if (error) {
    console.error("[games/publish] Supabase error:", {
      message:     error.message,
      code:        error.code,
      details:     error.details,
      hint:        error.hint,
      payloadKeys: Object.keys(row),
    });
    return json({
      error:   "Failed to save game.",
      details: error.message,
      code:    error.code  ?? null,
      hint:    error.hint  ?? null,
    }, 500);
  }

  const result = data as { id: string; local_game_id: string };
  return json({ ok: true, id: result.id, local_game_id: result.local_game_id });
}
